blank_issues_enabled: false
contact_links:
  - name: ❓ Support Question
    url: https://discourse.laminas.dev/c/questions/components/6
    about: 'This repository is only for reporting bugs and suggesting features. Support is provided via forums:'
  - name: 💡 Feedback Wanted
    url: https://discourse.laminas.dev
    about: 'Discuss and get feedback on ideas on our forums:'
